# Generated by Django 4.1.2 on 2022-10-26 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ActualProject', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='momentstodocument',
            old_name='bodyTextOfMoment',
            new_name='body_Text_Of_Moment',
        ),
        migrations.RenameField(
            model_name='momentstodocument',
            old_name='userOfMoment',
            new_name='created_by',
        ),
        migrations.RenameField(
            model_name='momentstodocument',
            old_name='dateOfMoment',
            new_name='date_Of_Moment',
        ),
        migrations.RenameField(
            model_name='momentstodocument',
            old_name='titleOfMoment',
            new_name='title_Of_Moment',
        ),
    ]
